import { DocumentationConfig, NavigationItem } from '@/types/documentation';
import { gettingStartedContent } from './gettingStarted';
import { configurationContent } from './configuration';
import { cliReferenceContent } from './cliReference';
import { mcpToolsContent } from './mcpTools';
import { restApiContent } from './restApi';

// Create navigation structure
// IDs must match kebab-case heading text generated by MarkdownRenderer
export const navigationItems: NavigationItem[] = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    href: '#getting-started-getting-started-with-local-memory',
    level: 0,
    children: [
      { id: 'what-is-local-memory', title: 'What is Local Memory?', href: '#getting-started-what-is-local-memory', level: 1 },
      { id: 'installation', title: 'Installation', href: '#getting-started-installation', level: 1 },
      { id: 'basic-workflow', title: 'Basic Workflow', href: '#getting-started-basic-workflow', level: 1 },
      { id: 'core-concepts', title: 'Core Concepts', href: '#getting-started-core-concepts', level: 1 },
      { id: 'license-management', title: 'License Management', href: '#getting-started-license-management', level: 1 },
      { id: 'integration-options', title: 'Integration Options', href: '#getting-started-integration-options', level: 1 },
      { id: 'common-workflows', title: 'Common Workflows', href: '#getting-started-common-workflows', level: 1 },
      { id: 'getting-help', title: 'Getting Help', href: '#getting-started-getting-help', level: 1 },
    ]
  },
  {
    id: 'configuration',
    title: 'Configuration',
    href: '#configuration-configuration-guide',
    level: 0,
    children: [
      { id: 'configuration-directory-structure', title: 'Directory Structure', href: '#configuration-directory-structure', level: 1 },
      { id: 'configuration-file-hierarchy', title: 'File Hierarchy', href: '#configuration-file-hierarchy', level: 1 },
      { id: 'core-configuration-sections', title: 'Core Configuration', href: '#configuration-core-configuration-sections', level: 1 },
      { id: 'service-integration', title: 'Service Integration', href: '#configuration-service-integration', level: 1 },
      { id: 'knowledge-configuration', title: 'Knowledge Configuration', href: '#configuration-knowledge-configuration', level: 1 },
      { id: 'session-management', title: 'Session Management', href: '#configuration-session-management', level: 1 },
      { id: 'environment-variables', title: 'Environment Variables', href: '#configuration-environment-variables', level: 1 },
      { id: 'configuration-profiles', title: 'Configuration Profiles', href: '#configuration-configuration-profiles', level: 1 },
    ]
  },
  {
    id: 'cli-reference',
    title: 'CLI Reference',
    href: '#cli-reference-cli-reference-guide',
    level: 0,
    children: [
      { id: 'cli-overview', title: 'Overview', href: '#cli-reference-overview', level: 1 },
      { id: 'cli-knowledge-hierarchy', title: 'Knowledge Hierarchy', href: '#cli-reference-knowledge-hierarchy', level: 1 },
      { id: 'core-memory-commands', title: 'Core Memory Commands', href: '#cli-reference-core-memory-commands', level: 1 },
      { id: 'knowledge-intake-commands', title: 'Knowledge Intake Commands', href: '#cli-reference-knowledge-intake-commands', level: 1 },
      { id: 'knowledge-evolution-commands', title: 'Knowledge Evolution Commands', href: '#cli-reference-knowledge-evolution-commands', level: 1 },
      { id: 'reasoning-commands', title: 'Reasoning Commands', href: '#cli-reference-reasoning-commands', level: 1 },
      { id: 'graph-status-commands', title: 'Graph & Status Commands', href: '#cli-reference-graph-status-commands', level: 1 },
      { id: 'system-administration', title: 'System Administration', href: '#cli-reference-system-administration', level: 1 },
      { id: 'response-formats-output', title: 'Response Formats', href: '#cli-reference-response-formats-output', level: 1 },
    ]
  },
  {
    id: 'mcp-tools',
    title: 'MCP Tools',
    href: '#mcp-tools-mcp-tools-reference',
    level: 0,
    children: [
      { id: 'mcp-overview', title: 'Overview', href: '#mcp-tools-overview', level: 1 },
      { id: 'mcp-knowledge-hierarchy', title: 'Knowledge Hierarchy', href: '#mcp-tools-knowledge-hierarchy', level: 1 },
      { id: 'core-memory-tools', title: 'Core Memory Tools', href: '#mcp-tools-core-memory-tools', level: 1 },
      { id: 'knowledge-intake-tools', title: 'Knowledge Intake Tools', href: '#mcp-tools-knowledge-intake-tools', level: 1 },
      { id: 'knowledge-evolution-tools', title: 'Knowledge Evolution Tools', href: '#mcp-tools-knowledge-evolution-tools', level: 1 },
      { id: 'reasoning-tools', title: 'Reasoning Tools', href: '#mcp-tools-reasoning-tools', level: 1 },
      { id: 'graph-status-tools', title: 'Graph Status Tools', href: '#mcp-tools-graph-status-tools', level: 1 },
      { id: 'integration-patterns', title: 'Integration Patterns', href: '#mcp-tools-integration-patterns', level: 1 },
    ]
  },
  {
    id: 'rest-api',
    title: 'REST API',
    href: '#rest-api-rest-api-reference',
    level: 0,
    children: [
      { id: 'api-overview', title: 'Overview', href: '#rest-api-overview', level: 1 },
      { id: 'api-knowledge-hierarchy', title: 'Knowledge Hierarchy', href: '#rest-api-knowledge-hierarchy', level: 1 },
      { id: 'core-memory-endpoints', title: 'Core Memory Endpoints', href: '#rest-api-core-memory-endpoints', level: 1 },
      { id: 'knowledge-intake-endpoints', title: 'Knowledge Intake Endpoints', href: '#rest-api-knowledge-intake-endpoints', level: 1 },
      { id: 'ai-analysis-endpoints', title: 'AI Analysis Endpoints', href: '#rest-api-ai-analysis-endpoints', level: 1 },
      { id: 'graph-status-endpoints', title: 'Graph & Status Endpoints', href: '#rest-api-graph-status-endpoints', level: 1 },
      { id: 'response-formats', title: 'Response Formats', href: '#rest-api-response-formats', level: 1 },
      { id: 'pagination', title: 'Pagination', href: '#rest-api-pagination', level: 1 },
    ]
  }
];

// Documentation sections
export const documentationSections = [
  gettingStartedContent,
  configurationContent,
  cliReferenceContent,
  mcpToolsContent,
  restApiContent
];

// Main documentation configuration
export const documentationConfig: DocumentationConfig = {
  sections: documentationSections,
  navigation: navigationItems
};

export * from './gettingStarted';
export * from './configuration';
export * from './cliReference';
export * from './mcpTools';
export * from './restApi';
